# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - charusat-chatbot-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com//
        username: ${{ secrets.AzureAppService_ContainerUsername_f7b41381e6614883b1ee80380f5158ea }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b720e4c9347f4a1b823515f2a824a61f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com//${{ secrets.AzureAppService_ContainerUsername_f7b41381e6614883b1ee80380f5158ea }}/daksh511/charusat-chatbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'charusat-chatbot-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0505ba874fc54e398df9185ccb92cd05 }}
        images: 'github.com//${{ secrets.AzureAppService_ContainerUsername_f7b41381e6614883b1ee80380f5158ea }}/daksh511/charusat-chatbot:${{ github.sha }}'