name: Build and deploy container app to Azure Web App - charusat-chatbot-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub  # 🔥 FIXED: Use the correct registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push container image to Docker Hub  # 🔥 FIXED: Correct image tagging
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: daksh511/charusat-chatbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'charusat-chatbot-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0505ba874fc54e398df9185ccb92cd05 }}
        images: 'daksh511/charusat-chatbot:${{ github.sha }}'  # 🔥 FIXED: Correct image reference
